spring:
  profiles:
    active: -dev
---
server:
  port: 9201
spring:
  profiles: dev
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/
---
server:
  port: 9202
spring:
  profiles: test
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/